### ISSUE TITLE
Shibboleth 4.3 upgrade

### ISSUE THREAD

**Issue by mar235av** [UWIT-IAM/uw-idp-custom#18]
Shibboleth released version 4.3.0 on 1/19/2023. We are currently on 4.2.1, the immediately previous version. There are no significant changes in the new version that are likely to cause problems, so we should be able to execute a simple upgrade.
After a brief period to verify that 4.3 is stable, we should update. At the same time we should implement issue #13 to upgrade the OIDC plugin to the latest minor version.
This is expected to be the last release of the 4.X Shibboleth branch, the next version being 5.0 coming out later in 2023. That upgrade is expected to involve more effort.

**Comment by jdiverp** [comment]
ready to resolve?

**Comment by mar235av** [comment]
Resolved by permforming the 4.3.0 update via RFC-0770 on Mar 1, 2023.
