### ISSUE TITLE
Remove custom "remember me" cookie logic

### ISSUE THREAD

**Issue by chmc3** [UWIT-IAM/uw-idp-custom#42]
Currently the UW idP has custom logic for handling idP issued "remember me" cookies for 2FA login. This code should be commented out (or if removed documented elsewhere) as it is no longer in use with the new Duo 2FA flow.

**Comment by stea-uw** [comment]
Fixed in https://github.com/UWIT-IAM/uw-idp-custom/commit/874f9b14bbe726c63f61fe377c2598513eee0114#diff-99f61dbb6b77b9e178efc65cac8ed9d94479f5959f5004419d90efc36581c996 by @mar235av
