### ISSUE TITLE
Replace references to seneca3* servers with eds.u.washington.edu 

### ISSUE THREAD

**Issue by chmc3** [UWIT-IAM/uw-idp-custom#43]
Currently, the UW idP currently references the specific LDAP servers (seneca31, seneca32, seneca33) instead of the standard eds.u.washington.edu DNS name.
The directory service team has requested that this change be made. The first step is to determine where we reference LDAP so we know where this update needs to occur.

**Comment by stea-uw** [comment]
Fixed in https://github.com/UWIT-IAM/uw-idp-custom/commit/874f9b14bbe726c63f61fe377c2598513eee0114 by @mar235av
Small optional fix in progress at https://github.com/UWIT-IAM/uw-idp-custom/pull/47
