### ISSUE TITLE
Synchronize deployment with GitHub repo

### ISSUE THREAD

**Issue by mar235av** [UWIT-IAM/uw-idp-custom#48]
The UW-specific files included in our Shibboleth deployment are tracked in the uw-idp-custom GitHub repository. The release process for these files does not guarantee synchronization between the repo and the files deployed, so these have slightly drifted out of sync. These diffs need to be resolved, and the release process changed to ensure that they remain synchronized. This work will also generate an inventory of relevant files which will be useful for future parts of this project.

- [x] Inventory all files currently deployed to production.
- [x] Diff with a clone of the repo to identify separate populations of files: (a) files in sync with the repo; (b) files never checked into GitHub (e.g. secret credentials); (c) archive files (not in repo, will not be included in container), (d) files out of sync with the repo.
- [x] Check in files in group (d) above to bring the repo up to date.
- [x] Compare across all 8 servers to verify all servers have consistent state.
- [x] Revise deployment process. We will clone the repo to each server and use that clone to sync to the deployed files.

**Comment by mar235av** [comment]
I'm declaring this issue resolved. There are a few file updates that need to be pushed to production to finish the reconciliation, but I will track that effort as part of issue #61, along with the other changes we need to push before doing the actual upgrade.

**Comment by chmc3** [comment]
This effort was completed with the release of idP v5 on 2024-08-13
