### ISSUE TITLE
Secrets: Fix oidc.properties

### ISSUE THREAD

**Issue by mar235av** [UWIT-IAM/uw-idp-custom#53]
The conf/oidc.properties file contains a key with a secret value. The version checked into GitHub has this secret suppressed so that no secret information is exposed.
Following the modern Shibboleth style and best practice, this secret should be moved to a separate configuration file under the credentials/ directory. This file should then be synchronized between GitHub and the deployment.

**Comment by mar235av** [comment]
Completed. I moved the secret to credentials/secrets.properties (not checked in) and changed the config file to reference that location.

**Comment by chmc3** [comment]
This effort was completed with the release of idP v5 on 2024-08-13
