### ISSUE TITLE
Java upgrade

### ISSUE THREAD

**Issue by mar235av** [UWIT-IAM/uw-idp-custom#58]
Shibboleth 5.X requires a Java upgrade. We are currently using Java 11, and must upgrade to Java 17.
This is not a major concern as we have established a standard process for Java upgrades on our IdP servers.

Added note: this Java upgrade requires installing the Nashorn Shibboleth plugin. This plugin replaces the scripting language that was included with Java 11 but dropped after Java 14.

**Comment by mar235av** [comment]
Completed. Installed Eclipse Temurin (Adoptium) version 17.0.11+9, the latest availabler version of Java 17.
Installed the Shibboleth nashorn plugin. Required a rebuild of the war, which I deployed to dev and tested with the new Java version.

**Comment by chmc3** [comment]
This effort was completed with the release of idP v5 on 2024-08-13
