### ISSUE TITLE
Tomcat upgrade

### ISSUE THREAD

**Issue by mar235av** [UWIT-IAM/uw-idp-custom#60]
Shibboleth 5.X requires an upgrade from our current Tomcat 9.X to version 10.X.

**Comment by mar235av** [comment]
I have opened a request to Unix Engineering asking for a meeting to discuss how to accomplish this required Tomcat upgrade.

**Comment by mar235av** [comment]
Unix Engineering is reviewing their processes for Tomcat upgrades. We expect an update by Wed 6/26.

**Comment by mar235av** [comment]
UE has built a version of Tomcat 10 and is able to deploy it from ref to our servers.
However, I misread the upgrade instructions. Shibboleth version 4 can only work with Tomcat 9, and Shibboleth 5 can only work with Tomcat 10, due to a change in package naming between the versions.
We will need to bundle the Tomcat and Shibboleth 5 upgrade steps together, but first do the other pre-upgrade steps.

**Comment by mar235av** [comment]
Marking this as complete. UE deployed a Tomcat 10.1 version to idpdev11. I was able to start it, and startup failed when it reached a problem in the (updated) Shibboleth 5 web app.
There may be other issues to address here, but I will track those as separate issues since, at this point as far as we know, Tomcat 10 is working as expected.

**Comment by chmc3** [comment]
This effort was completed with the release of idP v5 on 2024-08-13
