### ISSUE TITLE
pre-upgrade deployment to prod

### ISSUE THREAD

**Issue by mar235av** [UWIT-IAM/uw-idp-custom#61]
Before doing the 5.X upgrade in production, we will want to do a pre-update change that includes the following:

- [ ] Java upgrade (to Java 17)
- [ ] Updates to fix deprecation warnings
- [ ] Cleanup of our custom files (remove archive files, finish sync with GitHub repo)

**Comment by chmc3** [comment]
This effort was completed with the release of idP v5 on 2024-08-13
