### ISSUE TITLE
Disable warning configuration

### ISSUE THREAD

**Issue by mar235av** [UWIT-IAM/uw-idp-custom#62]
For the Google storage limit project, we configured a warning message for Shibboleth that would be displayed to users in a particular GWS group (the membership of that group managed by the project team).
That project has now concluded. The project team has removed all members from the control group, so this warning is no longer active for any users.
While updating Shibboleth configuration, we should disable this warning configuration so that it will stop making an unnecessary group membership lookup.

**Comment by chmc3** [comment]
This effort was completed with the release of idP v5 on 2024-08-13
