### ISSUE TITLE
Rebuild custom modules

### ISSUE THREAD

**Issue by mar235av** [UWIT-IAM/uw-idp-custom#63]
We have a set of custom modules built and deployed with Shibboleth. These are currently compiled against the Shibboleth 4.X API and will need to be re-built using the Shibboleth 5.X API. The affected modules are

- [x] uw-duo-bypass
- [x] uw-google-intercept
- [x] uw-http-client
- [x] uw-session-intercept
- [x] uw-slack-intercept
- [x] uw-username-lookup

It is unlikely but possible that API changes may require code changes, in addition to a simple re-compile.
After re-building, these will need to be bundled into the build of the 5.X war per standard process (install in edit-webapp directory).

**Comment by mar235av** [comment]
Completed. The required changes fell into the following categories;
1. Updating all library versions in the pom.xml to modern versions, including shib libraries (5.1.2).
2. Migration of various javax.* packages to jakarta.* packages. Required updating library names in pom.xml, relevant imports in Java code, and in some cases adding the jakarta-annotations package as a dependency in pom.xml.
3. A few minor code changes required due to changes in the Shibboleth API.
4. Updating the maven compiler configuration to specify Java 17 as the release target.

I rolled the version numbers of each of these plugins to the next minor version number.

**Comment by mar235av** [comment]
Marking this issue as resolved. There may be additional changes required, but I will track those as separate issues childed from the "Resolve unknowns" issue.

**Comment by chmc3** [comment]
This effort was completed with the release of idP v5 on 2024-08-13
