### ISSUE TITLE
pre-upgrade deploy and test on eval

### ISSUE THREAD

**Issue by mar235av** [UWIT-IAM/uw-idp-custom#66]
Once we have completed the pre-upgrade steps (including upgrading Java, and configuration updates), this issue tracks the effort to deploy this onto eval and run the manual and automated tests to validate.
The other deliverable from this effort is the precise list of steps needed to push this to production.

A reminder that all of this is pre-work that must be completed before performing the actual 5.X upgrade.

**Comment by chmc3** [comment]
This effort was completed with the release of idP v5 on 2024-08-13
