### ISSUE TITLE
deployment synchronization script

### ISSUE THREAD

**Issue by mar235av** [UWIT-IAM/uw-idp-custom#69]
Once the GitHub repository and the deployment have been fully synchronized, we will reach the state that
1. All files in the repository will match the same files deployed.
2. All files deployed in the source-controlled directories will match the same files in the repository, except for a small number of itemized exceptions that do not exist in the repository.
3. The deployment will contain additional directories not reflected in the repository at all (for example, the directories that hold the client metadata and the secrets).

We will then write a script that compares the repository and the deployment and use this during deployments to verify that the repository and deployment are always properly synchronized.

**Comment by mar235av** [comment]
Completed. I tested the script on dev and used it to finish the synchronization of the repository and the deployment directory.

**Comment by chmc3** [comment]
This effort was completed with the release of idP v5 on 2024-08-13
