### ISSUE TITLE
Resolve unknown Tomcat/Shib 5 issues

### ISSUE THREAD

**Issue by mar235av** [UWIT-IAM/uw-idp-custom#76]
This issue is a placeholder for whatever unknown issues will be discovered once we upgrade to Tomcat 10 and Shibboleth 5.X. Some things I am watching:
1. Tomcat configuration, particularly any possible changes in the server configuration. It is hard to know what might have changed between these major versions.
2. The Shibboleth release notes suggest four or five possible minor configuration issues that could impact us, that can only be discovered once we are running the new version.
3. In particular, we may need to rewrite our giant function that determines if a user needs the second factor on login, as there is an indication that a change puts a limit on the maximum allowable size of such a function, less than its current size.

**Comment by chmc3** [comment]
This effort was completed with the release of idP v5 on 2024-08-13
